### ISSUE TITLE
一些使用建议

### ISSUE THREAD

**Issue by GershonWang** [gfdgd-xi/deep-wine-runner#1]
1.显示建议：大佬，每次打开运行器都是出现在界面的左上角0，0坐标点，能不能小小的优化一下在界面居中显示呢，这样省去了点开界面还要拖拽到界面中间操作了
2.文件目录建议：右键exe文件使用wine运行器，打开界面后，“选择你要使用的wine容器”地址能不能再根据要wine的exe程序名称再多补一层文件夹，这样方便每个wine程序的独立化，要不然多个程序都散落在一个.wine文件夹里面了

**Comment by gfdgd-xi** [comment]
这个建议不错，我明天改一下

**Comment by gfdgd-xi** [comment]
第一项已经实现了，第二项要动的地方有点多，就没弄了

**Comment by GershonWang** [comment]
感谢大佬采纳建议

**Comment by GershonWang** [comment]
不过我发现1.6.0版本的居中显示，在我双屏的情况下，程序被分割在俩屏显示了！233~~

**Comment by gfdgd-xi** [comment]
估计是获取分辨率的方式把两个屏幕的分辨率加到一起了，因为我的另一个显示屏好像高压模块坏了，所以也就没有测试在双屏的情况
我尽快解决

**Comment by gfdgd-xi** [comment]
![图片](https://user-images.githubusercontent.com/73065138/178173163-15a91c00-2d53-4210-b9a5-501f484decd8.png)
基本实现在主显示器居中显示窗口，因为这个分辨率获取的函数是自己实现的，可能有局限性，将会改为在设置里选择性打开

**Comment by GershonWang** [comment]
其实感觉还有一个方便的方案。就是记录用户上次使用习惯，包括左上角左边点位置以及程序的宽高长度

**Comment by gfdgd-xi** [comment]
已完成优化 Wine 容器路径
详细见 https://github.com/gfdgd-xi/deep-wine-runner/pull/2
