### ISSUE TITLE
大大会考虑打包到其他非Debian系统上吗

### ISSUE THREAD

**Issue by Cheng-MaoMao** [gfdgd-xi/deep-wine-runner#7]
我是个Linux新手，很喜欢大大的软件真的很方便配置Wine，但是我们老师有要求使用Fedora，不知道大大以后会不会考虑做其他系统的版本？

**Comment by gfdgd-xi** [comment]
用离线版本就可以了

**Comment by gfdgd-xi** [comment]
当然如果有条件肯定会考虑移植到非debian发行版

**Comment by gfdgd-xi** [comment]
现在 3.7.0 已结移植到 Fedora 了
